#!/bin/sh

if ! [ -e "$1" ]; then
    echo "[Usage] ./test PATH_TO_LIBERTY"
    exit 1
fi


# ctrl.v; partitioning in 5; threshold 0.02; sequential mode
python3 ../greedy.py -i ctrl.v -lib ${1} -o ctrl1_output -ts 0.02 -n 5

# ctrl.v; not specify partition number; threshold 0.03; parallel mode
python3 ../greedy.py -i ctrl.v -tb 10000 -lib ${1} -o ctrl2_output -ts 0.03 --parallel

# ctrl.v; not specify partition number; threshold 0.03; step size 2; parallel mode
python3 ../greedy.py -i ctrl.v -lib ${1} -o ctrl3_output -ts 0.03 -ss 2 --parallel

# adder.v; not specify partition number; threshold 0.02; parallel mode
python3 ../greedy.py -i adder.v -tb 5000 -lib ${1} -o adder_output -ts 0.2 --parallel

# max.v; partitioning in 50; threshold 0.015; step_size 2; parallel mode
python3 ../greedy.py -i max.v -tb 4000 -lib ${1} -o max_output -n 50 -ts 0.015 -ss 2 --parallel

# sin.v; two-level partitioning; threshold 0.015; step_size 5; parallel mode
# python3 ../recursive.py -i sin.v -tb sin_tb.v -lib ${1} -o sin_output -ts 0.015 -ss 5 --parallel

