/* Generated by Yosys 0.7+ (git sha1 3de0568, gcc 7.4.0-1ubuntu1~16.04~ppa1 -fPIC -Os) */

module adder_28(pi0, pi1, pi2, pi3, pi4, pi5, pi6, pi7, po0, po1, po2, po3, po4);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  input pi0;
  input pi1;
  input pi2;
  input pi3;
  input pi4;
  input pi5;
  input pi6;
  input pi7;
  output po0;
  output po1;
  output po2;
  output po3;
  output po4;
  INVx1_ASAP7_75t_L _58_ (
    .A(_12_),
    .Y(_16_)
  );
  INVx1_ASAP7_75t_L _59_ (
    .A(_13_),
    .Y(_17_)
  );
  NAND2xp33_ASAP7_75t_L _60_ (
    .A(_16_),
    .B(_17_),
    .Y(_19_)
  );
  NAND2xp33_ASAP7_75t_L _61_ (
    .A(_12_),
    .B(_13_),
    .Y(_20_)
  );
  NAND2xp33_ASAP7_75t_L _62_ (
    .A(_20_),
    .B(_19_),
    .Y(_24_)
  );
  INVx1_ASAP7_75t_L _63_ (
    .A(_45_),
    .Y(_23_)
  );
  NAND2xp33_ASAP7_75t_L _64_ (
    .A(_55_),
    .B(_23_),
    .Y(_25_)
  );
  INVx1_ASAP7_75t_L _65_ (
    .A(_55_),
    .Y(_26_)
  );
  NAND2xp33_ASAP7_75t_L _66_ (
    .A(_45_),
    .B(_26_),
    .Y(_27_)
  );
  AND2x2_ASAP7_75t_L _67_ (
    .A(_45_),
    .B(_55_),
    .Y(_29_)
  );
  NOR2xp33_ASAP7_75t_L _68_ (
    .A(_45_),
    .B(_55_),
    .Y(_31_)
  );
  OAI21xp33_ASAP7_75t_L _69_ (
    .A1(_31_),
    .A2(_29_),
    .B(_20_),
    .Y(_32_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _70_ (
    .A1(_25_),
    .A2(_27_),
    .B(_20_),
    .C(_32_),
    .Y(_57_)
  );
  NAND2xp33_ASAP7_75t_L _71_ (
    .A(_14_),
    .B(_15_),
    .Y(_33_)
  );
  INVx1_ASAP7_75t_L _72_ (
    .A(_33_),
    .Y(_34_)
  );
  NOR2xp33_ASAP7_75t_L _73_ (
    .A(_14_),
    .B(_15_),
    .Y(_35_)
  );
  NOR2xp33_ASAP7_75t_L _74_ (
    .A(_35_),
    .B(_34_),
    .Y(_36_)
  );
  AND2x2_ASAP7_75t_L _75_ (
    .A(_12_),
    .B(_13_),
    .Y(_37_)
  );
  OR2x4_ASAP7_75t_L _76_ (
    .A(_45_),
    .B(_55_),
    .Y(_38_)
  );
  AOI21xp33_ASAP7_75t_L _77_ (
    .A1(_38_),
    .A2(_37_),
    .B(_29_),
    .Y(_39_)
  );
  XNOR2x2_ASAP7_75t_L _78_ (
    .A(_14_),
    .B(_15_),
    .Y(_40_)
  );
  NAND2xp33_ASAP7_75t_L _79_ (
    .A(_45_),
    .B(_55_),
    .Y(_41_)
  );
  O2A1O1Ixp33_ASAP7_75t_L _80_ (
    .A1(_16_),
    .A2(_17_),
    .B(_41_),
    .C(_31_),
    .Y(_42_)
  );
  OAI22xp33_ASAP7_75t_L _81_ (
    .A1(_36_),
    .A2(_39_),
    .B1(_40_),
    .B2(_42_),
    .Y(_18_)
  );
  INVx1_ASAP7_75t_L _82_ (
    .A(_21_),
    .Y(_43_)
  );
  INVx1_ASAP7_75t_L _83_ (
    .A(_22_),
    .Y(_44_)
  );
  NOR2xp33_ASAP7_75t_L _84_ (
    .A(_43_),
    .B(_44_),
    .Y(_46_)
  );
  NOR2xp33_ASAP7_75t_L _85_ (
    .A(_21_),
    .B(_22_),
    .Y(_47_)
  );
  NOR2xp33_ASAP7_75t_L _86_ (
    .A(_47_),
    .B(_46_),
    .Y(_48_)
  );
  INVx1_ASAP7_75t_L _87_ (
    .A(_35_),
    .Y(_49_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _88_ (
    .A1(_37_),
    .A2(_38_),
    .B(_29_),
    .C(_49_),
    .D(_34_),
    .Y(_50_)
  );
  XNOR2x2_ASAP7_75t_L _89_ (
    .A(_21_),
    .B(_22_),
    .Y(_51_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _90_ (
    .A1(_20_),
    .A2(_41_),
    .B(_31_),
    .C(_33_),
    .D(_35_),
    .Y(_52_)
  );
  OAI22xp33_ASAP7_75t_L _91_ (
    .A1(_50_),
    .A2(_48_),
    .B1(_51_),
    .B2(_52_),
    .Y(_28_)
  );
  INVx1_ASAP7_75t_L _92_ (
    .A(_47_),
    .Y(_53_)
  );
  A2O1A1Ixp33_ASAP7_75t_L _93_ (
    .A1(_12_),
    .A2(_13_),
    .B(_55_),
    .C(_45_),
    .Y(_54_)
  );
  OAI21xp33_ASAP7_75t_L _94_ (
    .A1(_26_),
    .A2(_20_),
    .B(_54_),
    .Y(_56_)
  );
  A2O1A1O1Ixp25_ASAP7_75t_L _95_ (
    .A1(_49_),
    .A2(_56_),
    .B(_34_),
    .C(_53_),
    .D(_46_),
    .Y(_30_)
  );
  assign _12_ = pi0;
  assign _13_ = pi4;
  assign po0 = _24_;
  assign _45_ = pi5;
  assign _55_ = pi1;
  assign po1 = _57_;
  assign _14_ = pi6;
  assign _15_ = pi2;
  assign po2 = _18_;
  assign _21_ = pi7;
  assign _22_ = pi3;
  assign po3 = _28_;
  assign po4 = _30_;
endmodule
